[project]
name = "saqml"
version = "0.1.0"
description = ""
authors = [{ name = "Melvin Strobl", email = "lc3267@kit.edu" }]
requires-python = ">=3.11,<3.12"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "qml-essentials",
    "dcor>=0.6,<0.7",
    "kedro>=1.3.1",
    "kedro-mlflow>=2.0.2",
    "mlflow>=3.11.1",
    "plotly>=6.7.0",
    "h5py>=3.16.0",
    "vector>=1.8.0",
    "nbformat>=5.10.4",
    "pytest>=9.0.3",
    "tenacity>=9.1.4",
    "kaleido>=1.2.0",
    "aiohttp>=3.13.5",
]

[project.scripts]
saqml = "saqml.__main__:main"

[project.entry-points."kedro.hooks"]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]
torchvision = [
    { index = "pytorch-cpu" },
]
qml-essentials = { git = "https://github.com/cirKITers/qml-essentials", rev = "40d0b27a70abe010d7871cec1fdd402b9ff884a8" }

[build-system]
requires = ["uv_build>=0.9.14,<0.10.0"]
build-backend = "uv_build"

[tool.kedro]
package_name = "saqml"
project_name = "saqml"
kedro_init_version = "0.19.6"
tools = [ "Testing", "Custom Logging", "Kedro Viz",]
example_pipeline = "False"
source_dir = "src"

[tool.pytest.ini_options]
addopts = "--cov-report term-missing --cov src/saqml -ra"

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = [ "pragma: no cover", "raise NotImplementedError",]

[tool.setuptools.dynamic.dependencies]
file = "requirements.txt"

[tool.setuptools.dynamic.version]
attr = "saqml.__version__"

[tool.setuptools.packages.find]
where = [ "src",]
namespaces = false
[tool.kedro_telemetry]
project_id = "c91edbf77bd8405a836ad827e8ab1b1e"
