data:
  domain: [-3.1415, 3.1415] # domain of x values
  omegas: 5
  amplitude: 0.5 #[1.0,1.0,1.0,1.0]

coefficients:
  samples: 300 #samples per parameter
  correlation_method: "pearson" #dcor, pearson, spearman
  log_coefficients: False
  zero_diagonal: True

expressibility:
  samples: 300 #samples per parameter scaling exp. with n qubits
  n_bins: 20 #scaling lin. with n qubits

model:
  n_qubits: 5
  n_layers: 1
  circuit_type: "ML_Bansatz" # Circuit_1, Circuit_5, Circuit_6, Circuit_9, Circuit_15, Circuit_18, Circuit_19, Hardware_Efficient, Strongly_Entangling, No_Entangling
  data_reupload: True
  output_qubit: -1
  initialization: "random" # random, zero-controlled, pi-controlled
  initialization_domain: [0, 6.283185307179586]
  layer_multiplier: 1
  noise_params:
    BitFlip: 0.0
    PhaseFlip: 0.0
    AmplitudeDamping: 0.0
    PhaseDamping: 0.0
    Depolarizing: 0.0

seed: 1000

n_control_values: 0 # for sweeping control values

training:
  steps: 1000
  learning_rate: 0.01
  batch_size: -1
  log_entangling: False
  positive_coeffs_only: True
  convergence:
    threshold: 5e-4 # threshold for the cost, -1 to disable
    gradient: -1 # threshold for the cost gradient, -1 to disable
    steps: 50 # gradient is checked for the last n steps (mavg)
